[package]
name = "simulated_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.7.0"
rand = "0.8.4"
rayon = "1.5.3"